#!/usr/bin/env bash
set -euo pipefail

# Cheap iteration script for the QTAIL_STE candidate on 1xH100.

RUN_ID="${RUN_ID:-qtail_1xh100}"
DATA_PATH="${DATA_PATH:-./data/datasets/fineweb10B_sp1024/}"
TOKENIZER_PATH="${TOKENIZER_PATH:-./data/tokenizers/fineweb_1024_bpe.model}"
VOCAB_SIZE="${VOCAB_SIZE:-1024}"
RUN_SCRIPT="${RUN_SCRIPT:-records/track_10min_16mb/2026-03-19_QTailSTE_Int6MLP3x/train_gpt.py}"
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-300}"
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-131072}"
TRAIN_SEQ_LEN="${TRAIN_SEQ_LEN:-2048}"
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-131072}"
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-0}"
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-50}"
QTAIL_STE="${QTAIL_STE:-1}"
QTAIL_START_FRAC="${QTAIL_START_FRAC:-0.82}"
MATRIX_LR="${MATRIX_LR:-0.02}"
SCALAR_LR="${SCALAR_LR:-0.02}"
TIED_EMBED_LR="${TIED_EMBED_LR:-0.03}"
MUON_MOMENTUM="${MUON_MOMENTUM:-0.99}"
MUON_MOMENTUM_WARMUP_START="${MUON_MOMENTUM_WARMUP_START:-0.92}"
MUON_MOMENTUM_WARMUP_STEPS="${MUON_MOMENTUM_WARMUP_STEPS:-1500}"
WARMDOWN_ITERS="${WARMDOWN_ITERS:-3000}"
GRAD_CLIP_NORM="${GRAD_CLIP_NORM:-0.3}"
MLP_HIDDEN="${MLP_HIDDEN:-1536}"
EVAL_SEQ_LEN="${EVAL_SEQ_LEN:-2048}"
EVAL_STRIDE="${EVAL_STRIDE:-256}"
FP16_TAIL_K_LAYERS="${FP16_TAIL_K_LAYERS:-2}"
FP16_TAIL_V_LAYERS="${FP16_TAIL_V_LAYERS:-0}"
FP16_TAIL_O_LAYERS="${FP16_TAIL_O_LAYERS:-0}"
FP16_EXTRA_WEIGHT_PATTERNS="${FP16_EXTRA_WEIGHT_PATTERNS:-}"

RUN_ID="${RUN_ID}" \
DATA_PATH="${DATA_PATH}" \
TOKENIZER_PATH="${TOKENIZER_PATH}" \
VOCAB_SIZE="${VOCAB_SIZE}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS}" \
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS}" \
TRAIN_SEQ_LEN="${TRAIN_SEQ_LEN}" \
VAL_BATCH_SIZE="${VAL_BATCH_SIZE}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY}" \
QTAIL_STE="${QTAIL_STE}" \
QTAIL_START_FRAC="${QTAIL_START_FRAC}" \
MATRIX_LR="${MATRIX_LR}" \
SCALAR_LR="${SCALAR_LR}" \
TIED_EMBED_LR="${TIED_EMBED_LR}" \
MUON_MOMENTUM="${MUON_MOMENTUM}" \
MUON_MOMENTUM_WARMUP_START="${MUON_MOMENTUM_WARMUP_START}" \
MUON_MOMENTUM_WARMUP_STEPS="${MUON_MOMENTUM_WARMUP_STEPS}" \
WARMDOWN_ITERS="${WARMDOWN_ITERS}" \
GRAD_CLIP_NORM="${GRAD_CLIP_NORM}" \
MLP_HIDDEN="${MLP_HIDDEN}" \
EVAL_SEQ_LEN="${EVAL_SEQ_LEN}" \
EVAL_STRIDE="${EVAL_STRIDE}" \
FP16_TAIL_K_LAYERS="${FP16_TAIL_K_LAYERS}" \
FP16_TAIL_V_LAYERS="${FP16_TAIL_V_LAYERS}" \
FP16_TAIL_O_LAYERS="${FP16_TAIL_O_LAYERS}" \
FP16_EXTRA_WEIGHT_PATTERNS="${FP16_EXTRA_WEIGHT_PATTERNS}" \
torchrun --standalone --nproc_per_node=1 "${RUN_SCRIPT}"
