#!/usr/bin/env bash
set -euo pipefail

# Exact-contract run for the current public frontier line once 8xH100 is available.

RUN_ID="${RUN_ID:-sota135_8xh100}"
DATA_PATH="${DATA_PATH:-./data/datasets/fineweb10B_sp1024/}"
TOKENIZER_PATH="${TOKENIZER_PATH:-./data/tokenizers/fineweb_1024_bpe.model}"
VOCAB_SIZE="${VOCAB_SIZE:-1024}"
RUN_SCRIPT="${RUN_SCRIPT:-records/track_10min_16mb/2026-03-19_OrthoInit_Int6_MLP3x_BigramHash_SmearGate/train_gpt.py}"
NPROC_PER_NODE="${NPROC_PER_NODE:-8}"
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-0}"
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-600}"
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-786432}"
TRAIN_SEQ_LEN="${TRAIN_SEQ_LEN:-2048}"
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-524288}"
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-0}"
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-200}"
EVAL_STRIDE="${EVAL_STRIDE:-64}"
QAT_ENABLED="${QAT_ENABLED:-0}"

RUN_ID="${RUN_ID}" \
DATA_PATH="${DATA_PATH}" \
TOKENIZER_PATH="${TOKENIZER_PATH}" \
VOCAB_SIZE="${VOCAB_SIZE}" \
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS}" \
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS}" \
TRAIN_SEQ_LEN="${TRAIN_SEQ_LEN}" \
VAL_BATCH_SIZE="${VAL_BATCH_SIZE}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY}" \
EVAL_STRIDE="${EVAL_STRIDE}" \
QAT_ENABLED="${QAT_ENABLED}" \
torchrun --standalone --nproc_per_node="${NPROC_PER_NODE}" "${RUN_SCRIPT}"
